apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth
  name: auth
  namespace: preymann
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8081
      targetPort: 80
  selector:
    io.kompose.service: auth
