apiVersion: v1
stringData:
  auth-client-secret: $K8S_AUTH_CLIENT_SECRET
kind: Secret
metadata:
  labels:
    io.kompose.service: auth-client-secret
  name: auth-client-secret
  namespace: preymann
type: Opaque
