apiVersion: v1
stringData:
  fluentbit-db-secret: $K8S_FLUENTBIT_DB_SECRET
kind: Secret
metadata:
  labels:
    io.kompose.service: fluentbit-db-secret
  name: fluentbit-db-secret
  namespace: preymann
type: Opaque
