apiVersion: v1
stringData:
  internal-api-secret: $K8S_INTERNAL_API_SECRET
kind: Secret
metadata:
  labels:
    io.kompose.service: internal-api-secret
  name: internal-api-secret
  namespace: preymann
type: Opaque
