apiVersion: v1
stringData:
  keycloak-admin-secret: $K8S_KEYCLOAK_ADMIN_SECRET
kind: Secret
metadata:
  labels:
    io.kompose.service: keycloak-admin-secret
  name: keycloak-admin-secret
  namespace: preymann
type: Opaque
