apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: preymann
spec:
  replicas: 1
  serviceName: nginx
  selector:
    matchLabels:
      io.kompose.service: nginx
  revisionHistoryLimit: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - name: nginx
          image: $CI_MIRROR_REGISTRY/nginx:stable-alpine
          imagePullPolicy: Always
          env:
            - name: DUMMY_RESTART_VAR
              value: $CI_PIPELINE_ID
          envFrom:
            - configMapRef:
                name: src-nginx--env
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "200Mi"
              cpu: "250m"
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: nginx-cm0
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /run
              name: nginx-tmpfs0
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: nginx-tmpfs0
        - configMap:
            name: nginx-cm0
          name: nginx-cm0
      imagePullSecrets:
        - name: secret-dockercfg
  volumeClaimTemplates:
    - metadata:
        name: nginx-cache
        labels:
          io.kompose.service: nginx-cache
      spec:
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 100Mi
        accessModes:
        - ReadWriteOnce



