apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: registry
  name: registry
  namespace: preymann
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8083
      targetPort: 80
  selector:
    io.kompose.service: registry
