apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: registry
  name: registry
  namespace: preymann
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registry
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: registry
    spec:
      containers:
        - env:
            - name: DUMMY_RESTART_VAR
              value: $CI_PIPELINE_ID
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: src-registry--env
          image: $CI_REGISTRY_IMAGE/registry:$CI_PIPELINE_ID
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "200Mi"
              cpu: "250m"
              ephemeral-storage: "100Mi"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  wget --no-verbose --tries=1 --spider  http://localhost/health || exit 1
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: registry
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /run/secrets/internal_api_secret
              name: internal-api-secret
              subPath: internal-api-secret
      restartPolicy: Always
      volumes:
        - name: internal-api-secret
          secret:
            items:
              - key: internal-api-secret
                path: internal-api-secret
            secretName: internal-api-secret
      imagePullSecrets:
        - name: secret-dockercfg
