apiVersion: v1
data:
  FLUENTBIT_HOSTNAME: fluentbit
  INTERNAL_API_SECRET_FILE: /run/secrets/internal_api_secret
  POSTGRES_DB: trinocular_repo
  POSTGRES_DEFAULT_DB: trinocular_db
  POSTGRES_HOST: postgres
  POSTGRES_INIT_SCRIPT: ./scripts/schema.sql
  POSTGRES_PORT: "5432"
  POSTGRES_SECRET_FILE: /run/secrets/postgres_secret
  POSTGRES_USER: trinocular_db_user
  SCHEDULER_NAME: scheduler
  SERVICE_NAME: repo
  TASK_CALLBACK_TIMEOUT: "500"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: repo-src-repo--env
  name: src-repo--env
  namespace: preymann
