apiVersion: v1
data:
  API_BRIDGE_NAME: api-bridge
  DB_FILE: /var/lib/frontend/database.db
  DB_INIT_SCRIPT: ./scripts/schema.sql
  ENABLE_DB_VIEWER: "true"
  FLUENTBIT_HOSTNAME: fluentbit
  HOST_NAME: localhost:8080
  INTERNAL_API_SECRET_FILE: /run/secrets/internal_api_secret
  MEMCACHED_HOST: memcached:11211
  PUBLIC_HTTPS: "true"
  REGISTRY_NAME: registry
  REPO_NAME: repo
  SCHEDULER_NAME: scheduler
  SERVICE_NAME: frontend
  SESSION_SECRET_FILE: /run/secrets/session_secret
  SHOW_ERROR_STACKTRACE: "true"
  VISUALIZATION_GROUP_NAME: visualizations
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: frontend-src-frontend--env
  name: src-frontend--env
  namespace: preymann
