apiVersion: v1
data:
  POSTGRES_DB: fluentbit
  POSTGRES_PASSWORD_FILE: /run/secrets/fluentbit_db_secret
  POSTGRES_USER: fluentbit_db_user
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: fluentbit-db-src-fluentbit-db--env
  name: src-fluentbit-db--env
  namespace: preymann
