apiVersion: v1
data:
  ACCEPTED_USER_EMAILS_FILE: "/run/auth/accepted-emails.txt"
  ADMIN_USER_ROLE: "trinocular_admin"
  CLIENT_NAME: trinocular_client
  CLIENT_SECRET_FILE: /run/secrets/auth_client_secret
  ERROR_URL: https://${K8S_DEPLOY_HOSTNAME}/error
  FLUENTBIT_HOSTNAME: fluentbit
  HOST_NAME: ${K8S_DEPLOY_HOSTNAME}/auth
  ISSUER_URL: http://keycloak:8080/realms/trinocular
  LOGIN_URL: https://${K8S_DEPLOY_HOSTNAME}/repos
  LOGOUT_URL: https://${K8S_DEPLOY_HOSTNAME}
  MEMCACHED_HOST: memcached:11211
  PASS_THROUGH_MODE: "false"
  PUBLIC_HTTPS: "true"
  SERVICE_NAME: auth
  SESSION_SECRET_FILE: /run/secrets/session_secret
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: auth-src-auth--env
  name: src-auth--env
  namespace: preymann
