apiVersion: v1
data:
  NGINX_SERVER_PORT: "80"
  NGINX_SERVER_HOST: trinocular.apps.student.inso-w.at
  NGINX_KEYCLOAK_PORT: "80"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx-src-nginx--env
  name: src-nginx--env
  namespace: preymann
