apiVersion: v1
data:
  NGINX_DNS_SEARCH: preymann.svc.cluster.local
  NGINX_SERVER_PORT: "80"
  NGINX_SERVER_HOST: ${K8S_DEPLOY_HOSTNAME}
  NGINX_KEYCLOAK_PORT: "8080"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx-src-nginx--env
  name: src-nginx--env
  namespace: preymann
