apiVersion: v1
data:
  DATABASE_HOST: fluentbit-db
  DATABASE_PORT: "5432"
  DATABASE_USER: fluentbit_db_user
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: fluentbit-src-fluentbit--env
  name: src-fluentbit--env
  namespace: preymann
